### ISSUE TITLE
Markdown rendering script stucks

### ISSUE THREAD

**Issue by raffaeleflorio** [evilsocket/arc#80] opened 2017-12-13 17:21 UTC
When Markdown is being rendered, the application stucks. On my PC this is caused when the text is, approximately, bigger than 34KB.
Other types of rendering doesn't cause stuck.

**Comment by evilsocket** [comment] 2017-12-13 19:19
On which browser and os?

**Comment by evilsocket** [comment] 2017-12-13 19:28
This looks browser or os specific, I'm not able to reproduce the issue with about 100Kb of markdown on latest Firefox and Chromium on Ubuntu.

**Comment by raffaeleflorio** [comment] 2017-12-13 19:33
I tried with Firefox 57 on Fedora.

**Comment by evilsocket** [comment] 2017-12-18 16:18
It looks like a very os-browser-version specific issue, I will close this for now unless someone else will report the same kind of behaviour in newer releases.

**Closed by evilsocket** 2017-12-18 16:18 UTC
Labels: bug, can't reproduce
